org.gradle.jvmargs=-Xmx2G
org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home

enabledPlatforms=fabric,neoforge

version=1.16.6
group=earth.terrarium.adastra

minecraftVersion=1.21.11
mixinExtrasVersion=0.4.1
parchmentVersion=2025.07.18

modMenuVersion=17.0.0-beta.1
reiVersion=21.11.814
jeiVersion=27.4.0.15

patchouliVersion=81
shimmerVersion=0.2.3

athenaVersion=4.4.0
cadmusVersion=2.0.0-alpha.5
argonautsVersion=2.0.0-alpha.5

resourcefulLibVersion=3.11.0
resourcefulConfigVersion=3.11.2
commonStorageLibVersion=0.0.8